import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: '25px',
  },
  base: {},
  error: {
    backgroundColor: 'orange',
  },
  input: {
    backgroundColor: '#333333',
    color: '#ffffff',
    marginBottom: '15px',
    height: '60px',
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
  },
  inputFocus: {
    backgroundColor: '#444444',
    color: '#ffffff',
    marginBottom: '15px',
    height: '60px',
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: '15px',
    height: '50px',
    width: '100%',
    borderRadius: '5px',
    borderWidth: '1px',
    borderColor: 'white',
    color: 'white',
    fontSize: '16px',
    fontWeight: '400',
  },
  buttonValid: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: '15px',
    height: '50px',
    width: '100%',
    borderRadius: '5px',
    borderWidth: '1px',
    borderColor: '#e50914',
    color: 'white',
    fontSize: '16px',
    fontWeight: '400',
    backgroundColor: '#e50914',
  },
  subTitle: {
    color: 'white',
    textAlign: 'center',
    marginBottom: '15px',
    fontSize: '18px',
  },
  text: {
    color: 'white',
    textAlign: 'center',
    marginBottom: '15px',
    fontSize: '16px',
  },
  textSmall: {
    color: '#757575',
    textAlign: 'center',
    marginVertical: '15px',
    fontSize: '12px',
  },
});

export default styles;
